### ISSUE TITLE
Prevent sleep when on charger

### ISSUE THREAD

**Issue by karlkashofer** [milky-sway/pinephone-scripts#4]
I usually keep my PP on the charger during night, which prevents sleep and thus the normal gnome-clocks alarm clock works. If phone is sleeping, the alarm does not go off. Additionally, i keep PP on charger while doing stuff on it via ssh, again this prevents it from sleeping in mid-sentence.

So, could you please adapt the script so it does not sleep while on charger ?

**Comment by milky-sway** [comment]
Sorry, have been very busy in the past weeks. Yes, that is easily possible, will add it to the script.
To be honest, I usually just stop the sleepwalk service when I'm at home.
Thanks for the suggestion.
